services:
  pritunl-mongo:
    image: mongo:6.0.15-rc0-jammy
    container_name: pritunl-mongo
    restart: unless-stopped
    volumes:
      - ./_DATA/pritunl/mongodb:/data/db
    networks:
      - vpn-network

  pritunl:
    image: rafiibrahim8/pritunl-warp:latest
    container_name: pritunl
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      - pritunl-mongo
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
        bind:
          create_host_path: false
    environment:
      MONGODB_URI: mongodb://pritunl-mongo:27017/pritunl
      TZ: UTC
    networks:
      - vpn-network
    ports:
      - mode: ingress
        target: "${VPN_PORT:-1194}"
        published: "${VPN_PORT:-1194}"
        protocol: "udp"
        x-port-name: "OpenVPN"
      - mode: ingress
        target: "443"
        published: "${WEBSERVER_PORT:-8573}"
        protocol: "tcp"
        x-port-name: "Web UI"
    cap_add:
      - NET_ADMIN

networks:
  vpn-network:
    name: vpn-network
